model:
  name: "FactorQVAE"
  group_count: 3
  n_blk_per_group: 2
  channel: 128
  hidden_dim: 128
  input_channel: 64
  codebook:
    num_embeddings: 128
    embedding_dim: 2
    init_type: "normal"
  quantizer:
    name: "RelaxedVQQuantizer"
    temp: 0.7
    kl_weight: 5e-3
  discriminator:
    gamma: 5e-4
data:
  name: "ClockDataModule"
  data_path: "./datasets/clock"
  img_size: 256
  num_latents: 15
  batch_size: 64
  num_workers: 8
train:
  reconst_loss: "F.l1_loss"
  max_steps: 150000
  optimizer: "torch.optim.Adam"
  vae_lr: 5e-4
  vae_lr_iter: 75000
  disc_lr: 5e-4
  disc_lr_iter: 75000
  check_val_every_n_epoch: 1
  seed: 1
