model:
  name: "QLAE"
  group_count: 3
  n_blk_per_group: 2
  channel: 128
  hidden_dim: 128
  input_channel: 64
  codebook:
    num_embeddings: 16
    embedding_dim: 1
  quantizer:
    name: "LatentQuantizer"
    commit_coeff: 1e-2
    quantize_coeff: 1e-2

# 主要修改這邊
data:
  name: "ClockDataModule"
  data_path: "./datasets/NHATclock" # 資料集路徑
  img_size: 128 # 訓練圖片解析度
  num_latents: 12 # 潛在特徵數量
  batch_size: 4 # batch size
  num_workers: 8
train:
  reconst_loss: "F.mse_loss"
  max_steps: 100000
  optimizer: "torch.optim.Adam"
  vae_lr: 1e-3
  vae_lr_iter: 50000
  check_val_every_n_epoch: 1
  seed: 1
